config/routes.rb
Gamesapp::Application.routes.draw do
  resources :post1s

  resources :forums do
  resources :post1s
  end

  resources :lineitem2s

  resources :order1s

  resources :carts

  resources :admin1s

  resources :stores

  resources :posts

  resources :table1s

  resources :result1s

  resources :match1s

  resources :competitors
  
  resources :result1s do
  resources :posts
  end

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  get "pages/home"

  get "pages/about"

  resources :members

  resources :teams
  match '/search',  :to => 'teams#search'
   match '/msearch',  :to => 'members#search'
  
   match '/about', :to => 'pages#about'
  match '/signin', :to => 'sessions#new'
  match '/signout',:to => 'sessions#destroy'
  resources:sessions

   root :to => 'pages#home'

end

app/models/admin1.rb
class Admin1 < ActiveRecord::Base
has_secure_password
validates_presence_of :name  
validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/} 
end

app/models/cart.rb
class Cart < ActiveRecord::Base
has_many :lineitem2s, dependent: :destroy
def total_price
lineitem2s.to_a.sum { |item| item.total_price }
end

end

app/models/competitor.rb
class Competitor < ActiveRecord::Base
has_many :match1s
validates_presence_of :team  , :gamertag
has_secure_password

end

app/models/forum.rb
class Forum < ActiveRecord::Base
belongs_to :member
has_many :post1s, :dependent => :destroy
end

app/models/lineitem2.rb
class Lineitem2 < ActiveRecord::Base
belongs_to :store
belongs_to :order1
belongs_to :cart
def total_price
store.price 
end

end

app/models/match1.rb
class Match1 < ActiveRecord::Base
belongs_to :team
belongs_to :member
belongs_to :competitor
has_many :result1s
end

app/models/member.rb
class Member < ActiveRecord::Base
has_many :order1s
has_secure_password
belongs_to :team
has_many :match1s
has_many :forums
has_many :posts, :dependent => :destroy
has_many :post1s, :dependent => :destroy
validates_presence_of :name  , :gamertag
validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/} 
geocoded_by :address
	after_validation :geocode, :if => :address_changed?
def self.search(search)
   search_condition = search + "%"
   find(:all, :conditions => ['Name LIKE  ?', search_condition])
end
end

app/models/order1.rb
class Order1 < ActiveRecord::Base
	has_many :lineitem2s
	belongs_to :store
	
	def add_lineitem2s_from_cart(cart)
		cart.lineitem2s.each do|item|
			item.cart_id = nil
			lineitem2s<<item
		end
	
end

end

app/models/post.rb
class Post < ActiveRecord::Base
belongs_to :member
belongs_to :result1

end

app/models/post1.rb
class Post1 < ActiveRecord::Base
belongs_to :member
belongs_to :forum
end

app/models/result1.rb
class Result1 < ActiveRecord::Base
belongs_to :match1
has_many :posts, :dependent => :destroy
end

app/models/store.rb
class Store < ActiveRecord::Base
mount_uploader :image, ImageUploader
has_many :lineitem2s
has_many :order1s, through: :lineitem2s
 before_destroy :ensure_not_referenced_by_any_lineitem2
#...
 private
 # ensure that there are no line items referencing this product
 def ensure_not_referenced_by_any_lineitem2
     if lineitem2s.empty?
      return true
       else
        errors.add(:base, 'Line Items present')
       return false
        end
    end
end

app/models/table1.rb
class Table1 < ActiveRecord::Base
belongs_to :team
end

app/models/team.rb
class Team < ActiveRecord::Base
has_many :members
has_one :table1
has_many :match1s
mount_uploader :image, ImageUploader
validates_presence_of :name , :arena , :logo
def self.search(search)
   search_condition = search + "%"
   find(:all, :conditions => ['Name LIKE  ?', search_condition])
end
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  # GET /forums
  # GET /forums.json
  def index
    @forums = Forum.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @forums }
    end
  end

  # GET /forums/1
  # GET /forums/1.json
  def show
    @forum = Forum.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @forum }
    end
  end

  # GET /forums/new
  # GET /forums/new.json
  def new
    @forum = Forum.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @forum }
    end
  end

  # GET /forums/1/edit
  def edit
    @forum = Forum.find(params[:id])
  end

  # POST /forums
  # POST /forums.json
  def create
    @forum = Forum.new(params[:forum])

    respond_to do |format|
      if @forum.save
        format.html { redirect_to @forum, notice: 'Forum was successfully created.' }
        format.json { render json: @forum, status: :created, location: @forum }
      else
        format.html { render action: "new" }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /forums/1
  # PUT /forums/1.json
  def update
    @forum = Forum.find(params[:id])

    respond_to do |format|
      if @forum.update_attributes(params[:forum])
        format.html { redirect_to @forum, notice: 'Forum was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forums/1
  # DELETE /forums/1.json
  def destroy
    @forum = Forum.find(params[:id])
    @forum.destroy

    respond_to do |format|
      format.html { redirect_to forums_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin1s_helper.rb
module Admin1sHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/post1s_helper.rb
module Post1sHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/forums/_form.html.erb
<%= form_for(@forum) do |f| %>
  <% if @forum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@forum.errors.count, "error") %> prohibited this forum from being saved:</h2>

      <ul>
      <% @forum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Title %><br />
    <%= f.text_field :Title %>
  </div>
  <div class="field">
    <%= f.label :Content %><br />
    <%= f.text_field :Content %>
  </div>
  <div class="field">
    <%= f.label :member_id %><br />
    <%= f.collection_select :member_id , Member.all, :id, :name  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/forums/edit.html.erb
<h1>Editing forum</h1>

<%= render 'form' %>

<%= link_to 'Show', @forum %> |
<%= link_to 'Back', forums_path %>

app/views/forums/index.html.erb
<%= image_tag("forum.png",:alt => "im sad", :size=> "400x100")%>

<table>
  <tr>
    <th>Title</th>
    <th>Created By</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @forums.each do |forum| %>
  <tr>
    <td><h4><%= forum.Title %></h4></td>
    <td><%= forum.member.name %></td>
    <td><%= link_to 'Show', forum %></td>
    <td><%= link_to 'Edit', edit_forum_path(forum) %></td>
    <td><%= link_to 'Destroy', forum, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Forum', new_forum_path %>

app/views/forums/new.html.erb
<h1>New forum</h1>

<%= render 'form' %>

<%= link_to 'Back', forums_path %>

app/views/forums/show.html.erb
<p id="notice"><%= notice %></p>
<h4><p>
  <b>Title:</b>
  <%= @forum.Title %>
</p>

<p>
  <b>Topic:</b>
  <%= @forum.Content %>
</p>

<p>
  <b>Member:</b>
  <%= @forum.member.name %>
</p></h4>


  <h2> Please leave a comment:</h2>
     <%= form_for([@forum, Post1.new]) do |f| %>
       <%= f.text_area :content, :rows => 3 %>
       <div class="actions">
        <%= f.submit "Post A Comment "%>
   </div>
<% end %>

<% if @forum.post1s.empty? %>
   <h3>you are the first to comment</h3>
<% else %>
<h2>what others felt</h2>
<% @forum.post1s.reverse.each do |post1| %>
   <p><%= post1.content %>
Posted <%= time_ago_in_words(post1.created_at) %> ago by 
       <%= post1.member.name %></p>
 <% end %>
<%end%>




<%= link_to 'Edit', edit_forum_path(@forum) %> |
<%= link_to 'Back', forums_path %>