config/routes.rb
Gamesapp::Application.routes.draw do
  resources :post1s

  resources :forums do
  resources :post1s
  end

  resources :lineitem2s

  resources :order1s

  resources :carts

  resources :admin1s

  resources :stores

  resources :posts

  resources :table1s

  resources :result1s

  resources :match1s

  resources :competitors
  
  resources :result1s do
  resources :posts
  end

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  get "pages/home"

  get "pages/about"

  resources :members

  resources :teams
  match '/search',  :to => 'teams#search'
   match '/msearch',  :to => 'members#search'
  
   match '/about', :to => 'pages#about'
  match '/signin', :to => 'sessions#new'
  match '/signout',:to => 'sessions#destroy'
  resources:sessions

   root :to => 'pages#home'

end

app/models/admin1.rb
class Admin1 < ActiveRecord::Base
has_secure_password
validates_presence_of :name  
validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/} 
end

app/models/cart.rb
class Cart < ActiveRecord::Base
has_many :lineitem2s, dependent: :destroy
def total_price
lineitem2s.to_a.sum { |item| item.total_price }
end

end

app/models/competitor.rb
class Competitor < ActiveRecord::Base
has_many :match1s
validates_presence_of :team  , :gamertag
has_secure_password

end

app/models/forum.rb
class Forum < ActiveRecord::Base
belongs_to :member
has_many :post1s, :dependent => :destroy
end

app/models/lineitem2.rb
class Lineitem2 < ActiveRecord::Base
belongs_to :store
belongs_to :order1
belongs_to :cart
def total_price
store.price 
end

end

app/models/match1.rb
class Match1 < ActiveRecord::Base
belongs_to :team
belongs_to :member
belongs_to :competitor
has_many :result1s
end

app/models/member.rb
class Member < ActiveRecord::Base
has_many :order1s
has_secure_password
belongs_to :team
has_many :match1s
has_many :forums
has_many :posts, :dependent => :destroy
has_many :post1s, :dependent => :destroy
validates_presence_of :name  , :gamertag
validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/} 
geocoded_by :address
	after_validation :geocode, :if => :address_changed?
def self.search(search)
   search_condition = search + "%"
   find(:all, :conditions => ['Name LIKE  ?', search_condition])
end
end

app/models/order1.rb
class Order1 < ActiveRecord::Base
	has_many :lineitem2s
	belongs_to :store
	
	def add_lineitem2s_from_cart(cart)
		cart.lineitem2s.each do|item|
			item.cart_id = nil
			lineitem2s<<item
		end
	
end

end

app/models/post.rb
class Post < ActiveRecord::Base
belongs_to :member
belongs_to :result1

end

app/models/post1.rb
class Post1 < ActiveRecord::Base
belongs_to :member
belongs_to :forum
end

app/models/result1.rb
class Result1 < ActiveRecord::Base
belongs_to :match1
has_many :posts, :dependent => :destroy
end

app/models/store.rb
class Store < ActiveRecord::Base
mount_uploader :image, ImageUploader
has_many :lineitem2s
has_many :order1s, through: :lineitem2s
 before_destroy :ensure_not_referenced_by_any_lineitem2
#...
 private
 # ensure that there are no line items referencing this product
 def ensure_not_referenced_by_any_lineitem2
     if lineitem2s.empty?
      return true
       else
        errors.add(:base, 'Line Items present')
       return false
        end
    end
end

app/models/table1.rb
class Table1 < ActiveRecord::Base
belongs_to :team
end

app/models/team.rb
class Team < ActiveRecord::Base
has_many :members
has_one :table1
has_many :match1s
mount_uploader :image, ImageUploader
validates_presence_of :name , :arena , :logo
def self.search(search)
   search_condition = search + "%"
   find(:all, :conditions => ['Name LIKE  ?', search_condition])
end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
before_filter :authorise, :only => [:new ,  :edit, :destroy]
  # GET /stores
  # GET /stores.json
  def index
  @stores = Store.all
  @cart = current_cart
 respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stores }
    end
  
  end
  

  # GET /stores/1
  # GET /stores/1.json
  def show
    @store = Store.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @store }
    end
  end

  # GET /stores/new
  # GET /stores/new.json
  def new
    @store = Store.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @store }
    end
  end

  # GET /stores/1/edit
  def edit
    @store = Store.find(params[:id])
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(params[:store])

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render json: @store, status: :created, location: @store }
      else
        format.html { render action: "new" }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stores/1
  # PUT /stores/1.json
  def update
    @store = Store.find(params[:id])

    respond_to do |format|
      if @store.update_attributes(params[:store])
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store = Store.find(params[:id])
    @store.destroy

    respond_to do |format|
      format.html { redirect_to stores_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin1s_helper.rb
module Admin1sHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/post1s_helper.rb
module Post1sHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/stores/_form.html.erb
<%= form_for(@store) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product %><br />
    <%= f.text_field :product %>
  </div>
  <div class="field">
    <%= f.label :picture %><br />
    <%= f.text_field :picture %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :stock %><br />
    <%= f.text_field :stock %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing store</h1>

<%= render 'form' %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<%= image_tag("store.png",:alt => "im sad", :size=> "400x100")%>
<% if notice %>

<% end %>
 <% if !@stores.nil? %>	
  <% @stores.each do |store| %>
   <div class="entry">
    <h4><%= store.product %></h4>
    <%= image_tag(store.picture, :size => "100x100") %>
    <div class="price_line">
     <span class="price"><%= number_to_currency(store.price) %></span>
     <td><%= link_to 'Destroy', store, confirm: 'Are you sure?', method: :delete %></td>
      <%= button_to 'Add to Cart', lineitem2s_path(store_id: store), remote: true %>
     </div>
  </div>
<% end %>
<%end%>


<%= link_to 'New Product', new_store_path %>

app/views/stores/new.html.erb
<h1>New store</h1>

<%= render 'form' %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Product:</b>
  <%= @store.product %>
</p>

<p>
  <b>Picture:</b>
  <%= @store.picture %>
</p>

<p>
  <b>Price:</b>
  <%= @store.price %>
</p>
<p>
  <b>Stock:</b>
  <%= @store.stock %>
</p>


<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>