config/routes.rb
Gamesapp::Application.routes.draw do
  resources :post1s

  resources :forums do
  resources :post1s
  end

  resources :lineitem2s

  resources :order1s

  resources :carts

  resources :admin1s

  resources :stores

  resources :posts

  resources :table1s

  resources :result1s

  resources :match1s

  resources :competitors
  
  resources :result1s do
  resources :posts
  end

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  get "pages/home"

  get "pages/about"

  resources :members

  resources :teams
  match '/search',  :to => 'teams#search'
   match '/msearch',  :to => 'members#search'
  
   match '/about', :to => 'pages#about'
  match '/signin', :to => 'sessions#new'
  match '/signout',:to => 'sessions#destroy'
  resources:sessions

   root :to => 'pages#home'

end

app/models/admin1.rb
class Admin1 < ActiveRecord::Base
has_secure_password
validates_presence_of :name  
validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/} 
end

app/models/cart.rb
class Cart < ActiveRecord::Base
has_many :lineitem2s, dependent: :destroy
def total_price
lineitem2s.to_a.sum { |item| item.total_price }
end

end

app/models/competitor.rb
class Competitor < ActiveRecord::Base
has_many :match1s
validates_presence_of :team  , :gamertag
has_secure_password

end

app/models/forum.rb
class Forum < ActiveRecord::Base
belongs_to :member
has_many :post1s, :dependent => :destroy
end

app/models/lineitem2.rb
class Lineitem2 < ActiveRecord::Base
belongs_to :store
belongs_to :order1
belongs_to :cart
def total_price
store.price 
end

end

app/models/match1.rb
class Match1 < ActiveRecord::Base
belongs_to :team
belongs_to :member
belongs_to :competitor
has_many :result1s
end

app/models/member.rb
class Member < ActiveRecord::Base
has_many :order1s
has_secure_password
belongs_to :team
has_many :match1s
has_many :forums
has_many :posts, :dependent => :destroy
has_many :post1s, :dependent => :destroy
validates_presence_of :name  , :gamertag
validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/} 
geocoded_by :address
	after_validation :geocode, :if => :address_changed?
def self.search(search)
   search_condition = search + "%"
   find(:all, :conditions => ['Name LIKE  ?', search_condition])
end
end

app/models/order1.rb
class Order1 < ActiveRecord::Base
	has_many :lineitem2s
	belongs_to :store
	
	def add_lineitem2s_from_cart(cart)
		cart.lineitem2s.each do|item|
			item.cart_id = nil
			lineitem2s<<item
		end
	
end

end

app/models/post.rb
class Post < ActiveRecord::Base
belongs_to :member
belongs_to :result1

end

app/models/post1.rb
class Post1 < ActiveRecord::Base
belongs_to :member
belongs_to :forum
end

app/models/result1.rb
class Result1 < ActiveRecord::Base
belongs_to :match1
has_many :posts, :dependent => :destroy
end

app/models/store.rb
class Store < ActiveRecord::Base
mount_uploader :image, ImageUploader
has_many :lineitem2s
has_many :order1s, through: :lineitem2s
 before_destroy :ensure_not_referenced_by_any_lineitem2
#...
 private
 # ensure that there are no line items referencing this product
 def ensure_not_referenced_by_any_lineitem2
     if lineitem2s.empty?
      return true
       else
        errors.add(:base, 'Line Items present')
       return false
        end
    end
end

app/models/table1.rb
class Table1 < ActiveRecord::Base
belongs_to :team
end

app/models/team.rb
class Team < ActiveRecord::Base
has_many :members
has_one :table1
has_many :match1s
mount_uploader :image, ImageUploader
validates_presence_of :name , :arena , :logo
def self.search(search)
   search_condition = search + "%"
   find(:all, :conditions => ['Name LIKE  ?', search_condition])
end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/post1s_helper.rb
module Post1sHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gamesapp</title>
  <%= stylesheet_link_tag  "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css",  "application", :media => "all" %>
  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js", "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="banner">
<font size="3" color="green">aaron turner</font>
	<%= image_tag("logo.gif", :size => "400x70") %>
	<%= @page_title || "" %>
</div>
<% if flash %>
    <% flash.each do |key, value| %>   
       <div class="flash <%= key %>">
		<%= value %>
	</div>
    <% end %>
 <% end %>
 

<div id="nav">

	<ul>
	<% if !signed_in? %>
		<li><%= link_to "Sign In", signin_path %></li>
		<li><%= link_to "Register", new_member_path%></li>
	<% else %>
		<li>Signed in as <%= @current_member.name %></li>
		<li><%= link_to "Sign Out", signout_path %></li>

	<%end %>
		
		<li><%= link_to "Teams", teams_path%></li>
		<li><%= link_to "Members", members_path%></li>
		<li><%=link_to "Competitors", competitors_path %></li>
		<li><%= link_to "Create Match", new_match1_path %></li>
		<li><%= link_to "View Match", match1s_path %></li>
		<li><%= link_to "Results", result1s_path %></li>
		<li><%= link_to "Table", table1s_path%></li>
		<li><%= link_to "Store", stores_path%></li>
		<li><%= link_to "Forums", forums_path%></li>
		<li><%= link_to "Admin", admin1s_path%></li>
		<li><%= link_to "About", about_path%></li>
		
		
		
	</ul>
	<div id="columns">
    <div id="side">
    <div id="cart">
	<% if @cart %>
<%= render @cart %>
<% end %>
</div>
	<div id="footer">
        
</div>
   </div>
  </div>
 </div>
</head>

<%= yield %>


</body>
</html>